

python run_sglang_softthinking.py \
    --dataset "aime2024" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \

python run_sglang_softthinking.py \
    --dataset "aime2025" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \

python run_sglang_softthinking.py \
    --dataset "amc23" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \

python run_sglang_softthinking.py \
    --dataset "math500" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \

python run_sglang_softthinking.py \
    --dataset "gsm8k" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1500 \
    --num_gpus 1 \
    --num_samples 32 \

python run_sglang_softthinking.py \
    --dataset "gpqa_diamond" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \


python run_sglang_softthinking.py \
    --dataset "humaneval" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \

python run_sglang_softthinking.py \
    --dataset "mbpp" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \


python run_sglang_softthinking.py \
    --dataset "humaneval" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \
    --reeval \

python run_sglang_softthinking.py \
    --dataset "mbpp" \
    --model_name ********************************/SofT-GRPO-master/saved_weight/Deepeeek-Qwen-1.5B+GRPO \
    --max_topk 30 \
    --max_generated_tokens 32768 \
    --temperature 0.6 \
    --top_p 0.95 \
    --top_k 30 \
    --min_p 0.0 \
    --after_thinking_temperature 0.6 \
    --after_thinking_top_p 0.95 \
    --after_thinking_top_k 30 \
    --after_thinking_min_p 0.0 \
    --mem_fraction_static 0.8 \
    --start_idx 0 \
    --end_idx 1000 \
    --num_gpus 1 \
    --num_samples 32 \
    --reeval \


EOF